# Generated by Django 4.0 on 2021-12-17 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
